service: estudiantes-dynamodb
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}
  environment: 
    TABLE_ESTUDIANTE: estudiantes-${self:provider.stage}
    LOG_ENVIRONMENT: ${file(./serverless.env.yml):${opt:envrt}.LOGGER_ROOT_LEVEL}
    PATH_RESOURCES: /v1/idexud
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Update*
        - dynamodb:Delete*
      Resource: arn:aws:dynamodb:us-east-2:160185970927:table/estudiantes-${self:provider.stage}    

functions:
  create:
    handler: handler.create
    events:
       - http:
          path: ${self:provider.environment.PATH_RESOURCES}/create
          method: POST
    memorySize: 128
  update:
    handler: handler.update
    events:
       - http:
          path: ${self:provider.environment.PATH_RESOURCES}/update
          method: PUT
    memorySize: 128
  getAllItems:
    handler: handler.getAll
    events:
       - http:
          path: ${self:provider.environment.PATH_RESOURCES}/getAllItems
          method: GET
    memorySize: 128
  getItem:
    handler: handler.getItem
    events:
       - http:
          path: ${self:provider.environment.PATH_RESOURCES}/getItem/{codigoEstudiantil}
          method: GET
    memorySize: 128
  deleteItem:
    handler: handler.deleteItem
    events:
       - http:
          path: ${self:provider.environment.PATH_RESOURCES}/deleteItem/{codigoEstudiantil}
          method: DELETE
    memorySize: 128  